stages:
  - test
  - build

test:
  stage: test
  image: ${CI_REGISTRY}/bi-ido/bi-ido-registry/maven:3.8.6-openjdk-18
  script:
    - cd server && ./gradlew test

container:
  stage: build
  image: $CI_REGISTRY/ict/images/buildah:latest
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
    - buildah build --squash --tag $IMAGE_TAG .
    - buildah push $IMAGE_TAG
